services:
  postgres:
    image: postgres:17-alpine
    container_name: specpilot-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: specpilot
      POSTGRES_PASSWORD: specpilot
      POSTGRES_DB: specpilot
    ports:
      - '5432:5432'
    volumes:
      - specpilot_postgres_local_data:/var/lib/postgresql/data
    networks:
      - specpilot-local

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: specpilot-keycloak-local
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: specpilot
      KC_DB_PASSWORD: specpilot
    volumes:
      - ./infrastructure/keycloak:/opt/keycloak/data/import
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - specpilot-local

networks:
  specpilot-local:
    name: specpilot-local

volumes:
  specpilot_postgres_local_data:
    name: specpilot_postgres_local_data
