events {}

http {
  server {
  listen 80;
  server_name adrianmorillo.com www.adrianmorillo.com specpilot.adrianmorillo.com api.specpilot.adrianmorillo.com auth.adrianmorillo.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

  server {
  listen 80;
  server_name ci.adrianmorillo.com;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 503 "Jenkins service not deployed yet";
  }
}

  server {
    listen 443 ssl;
    server_name adrianmorillo.com www.adrianmorillo.com;

    ssl_certificate /etc/letsencrypt/live/adrianmorillo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/adrianmorillo.com/privkey.pem;
    
    location / {
      return 503 "Portfolio service not deployed yet";
    }
  }

  server {
    listen 443 ssl;
    server_name specpilot.adrianmorillo.com;

    ssl_certificate /etc/letsencrypt/live/adrianmorillo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/adrianmorillo.com/privkey.pem;

    location / {
      proxy_pass http://specpilot-frontend:80;
    }
  }

  server {
    listen 443 ssl;
    server_name api.specpilot.adrianmorillo.com;

    ssl_certificate /etc/letsencrypt/live/adrianmorillo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/adrianmorillo.com/privkey.pem;

    location / {
      proxy_pass http://specpilot-api:3000;
    }
  }

  server {
    listen 443 ssl;
    server_name auth.adrianmorillo.com;

    ssl_certificate /etc/letsencrypt/live/adrianmorillo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/adrianmorillo.com/privkey.pem;

    location / {
      proxy_pass http://keycloak:8080;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Port 443;
    }
  }
}